basic/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    
    path('register/', views.registerUser, name="register"),
    
    path('', views.profiles, name="profiles"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('account/', views.userAccount, name="account"),
    path('edit-account/', views.editAccount, name="edit-account"),
    path('create-skill/', views.createSkill, name="create-skill"),
    
    
    path('update-skill/<str:pk>/', views.updateSkill, name="update-skill"),
    path('delete-skill/<str:pk>/', views.deleteSkill, name="delete-skill"),
    
    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path('create-message/<str:pk>/', views.createMessage, name="create-message"),
]

basic/users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.



class Profile(models.Model):
    # ! the [user] is having a [One-To-One] relationship with a [user]->[model].
    # * The [user]->[model] is sometimes use for authentication.
    user            =  models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name            =  models.CharField(max_length=200, blank=True, null=True)
    email           =  models.EmailField(max_length= 500, blank= True, null=True)
    username        =  models.CharField(max_length=200, blank=True, null=True)
    location        =  models.CharField(max_length=200, blank=True, null=True)
    short_intro     =  models.CharField(max_length=200, blank=True, null=True)
    bio             =  models.TextField(blank=True, null=True)
    profile_image   =  models.ImageField(null=True, blank=True, upload_to = 'profiles/', default='profiles/user-default.png')
    social_github   =  models.CharField(max_length=200, blank=True, null=True)
    social_twitter  =  models.CharField(max_length=200, blank=True, null=True)
    social_linkedin =  models.CharField(max_length=200, blank=True, null=True)
    social_website  =  models.CharField(max_length=200, blank=True, null=True)
    social_facebook =  models.CharField(max_length=200, blank=True, null=True)
    created         =  models.DateTimeField(auto_now_add=True)
    id              =  models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    

    def __str__(self):
        return str(self.user.username)


class Skill(models.Model):
    # ! we are creating a parent->child [model] the parent is [Profile] while the child is [Skill]
    owner         =  models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    name          =  models.CharField(max_length=200, blank=True, null=True)
    description   =  models.TextField(null=True, blank=True)
    created       =  models.DateTimeField(auto_now_add=True)
    id            =  models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    

    def __str__(self):
        return str(self.name)
    
    
class Message(models.Model):
    sender      = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient   = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name        = models.CharField(max_length=200, null=True, blank=True)
    email       = models.EmailField(max_length=200, null=True, blank=True)
    subject     = models.CharField(max_length=200, null=True, blank=True)
    body        = models.TextField()
    # * unread message should be shown first.
    is_read     = models.BooleanField(default=False, null=True)
    created     = models.DateTimeField(auto_now_add=True, )
    id          = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True, editable=False)

    
    def __str__(self):
        return self.subject
    
    
    class Meta:
        ordering = ['is_read', '-created']

basic/users/templates/users/account.html
{% extends "main.html" %}
{% block title %}Dev-Connect / Profiles{% endblock %}
{% block content %}




  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src={{profile.profile_image.url}} />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>


              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
              {% endif %}

           
              {% if profile.social_facebook %}
                <li>
                  <a title="FaceBook" href="{{profile.social_facebook}}" target="_blank"><i class="im im-facebook"></i></a>
                </li>
              {% endif %}



              {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
              {% endif %}



              {% if profile.social_linkedln %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
              {% endif %}

              
              {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
              {% endif %}

              </ul>


              <a href="#" class="btn btn--sub btn--lg">Send Message</a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
            {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">

            {% for skill in skills %}

            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>
                  {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">

                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}">
                  <i class="im im-edit"></i>
                   Edit
                  </a>
                  <!-- ? [?next=/account] ? when we click on the link the extra value will be appended -->
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account">
                  <i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}



          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in projects %}

            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'project' project.id %}">
                  <img src="{{project.featured_image.url}}" alt="Project Thumbnail" />
                </a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'project' project.id %}">{{project.title}}</a>
                <p>
                 {{project.description|slice:"100"}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}">
                  <i class="im im-edit"></i> 
                  Edit
                </a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account">
                  <i class="im im-x-mark-circle-o"></i>
                  Delete
                </a>
              </td>
            </tr>
            {% endfor %}

          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

basic/users/templates/users/inbox.html
{% extends "main.html" %}

{% block title %}Inbox📧->Page{% endblock %}
 
{% load static %}
 {% block content %}
  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">
        {% for message in messageRequests %}
        {% if message.is_read == False %}
        <li class="message message--unread">
          {% else %}
        <li class="message">
          {% endif %}
          <a href="{% url 'message' message.id %}">
            <span class="message__author">{{message.name}}</span>
            <span class="message__subject">{{message.subject}}</span>
            <span class="message__date">{{message.created}}</span>
          </a>
        </li>
        {% endfor %}
      
      </ul>
    </div>
  </main>
{% endblock content %}

basic/users/templates/users/login_register.html
{% extends "main.html" %}

{% block title %}Auth🔐->Page{% endblock %}
 
{% load static %}
 {% block content %}
 
 {% if page == 'register' %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center"> 
      <a href="/">
        <img src=" {% static 'images/icon.svg' %} " alt="icon" />
      </a>
      <h3>Register an account</h3>
      <p>Create a new developer account</p>
    </div>

    <form action="{% url 'register' %}" method="post" class="form auth__form">
      {% csrf_token %} 
      
      {% for field in form %}

      <div class="form__field">
        <label for="formInput#text">{{field.label}}</label>
        {{field}}

        <!-- ! showing the helper text. -->
        <!-- {% if field.help_text %}
              <small>{{field.help_text}}</small>
            {% endif %} -->

        {% for error in field.errors %}
        <p style="color: red">{{error}}</p>
        {% endfor %}
      </div>
      {% endfor %}

      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Sign  Up" />
      </div>
    </form>
    <div class="auth__alternative">
      <p>Already have an Account?</p>
      <a href="{% url 'login' %}">Log In</a>
    </div>
  </div>
</div>

{% else %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src=" {% static 'images/icon.svg' %} " alt="icon" />
      </a>
      <h3>Account Login</h3>
      <p>Hello Developer, Welcome Back!</p>
    </div>

    <form method="POST" action="" class="form auth__form">
      {% csrf_token %}

      <!-- Input:Username -->
      <div class="form__field">
        <label for="formInput#text">Username: </label>
        <input
          class="input input--text"
          id="formInput#text"
          type="text"
          name="username"
          placeholder="Enter your username..."
        />
      </div>

      <!-- Input:Password -->
      <div class="form__field">
        <label for="formInput#password">Password: </label>
        <input
          class="input input--password"
          id="formInput#passowrd"
          type="password"
          name="password"
          placeholder="••••••••"
        />
      </div>
      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
        <a href="{% url 'reset_password' %}">Forget Password?</a>
      </div>
    </form>
    <div class="auth__alternative">
      <p>Don’t have an Account?</p>
      <a href="{% url 'register' %}">Sign Up</a>
    </div>
  </div>
</div>

{% endif %} 
{% endblock content %}

basic/users/templates/users/message.html
{% extends "main.html" %}
{% block title %}Message✉ ->  Page{% endblock %}


{% block content %}
  <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{message.subject}}</h4>
          <a href="profile.html" class="message__author">{{message.name}}</a>
          <p class="message__date">{{message.created}}</p>
          <div class="message__body">
            {{message.body|linebreaksbr}}
            <br /><br />
           
          </div>
      </div>
    </div>
  </main>

{% endblock content %}

basic/users/templates/users/message_form.html
{% extends "main.html" %}
{% block title %}Message / Form {% endblock %}

{% block content %}

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'user-profile' recipient.id %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}


                    {% if request.user.is_authenticated == False %}
                    <div class="form__field">
                        <label for="formInput#text">{{form.name.label}}</label>
                            {{form.name}}
                            </div>


                        <div class="form__field">
                            <label for="formInput#text">{{form.email.label}}</label>
                                {{form.email}}
                                </div>
                    {% endif %}
                    <div class="form__field">
                        <label for="formInput#text">{{form.subject.label}}</label>
                            {{form.subject}}
                            </div>


                        <div class="form__field">
                            <label for="formInput#text">{{form.body.label}}</label>
                                {{form.body}}
                                </div>

                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>



{% endblock content %}

basic/users/templates/users/profile_form.html
{% extends "main.html" %}
{% block title %}Form / Profile{% endblock %}


{% block content %}


    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" action="{% url 'edit-account' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                            {% for field in form %}
                                 <!-- Input:Text -->
                                <div class="form__field">
                                    <label for="formInput#text">{{field.label}}</label>
                                    {{field}}
                                </div>

                            {% endfor %}


                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>





{% endblock content %}

basic/users/templates/users/profiles.html
{% extends "main.html" %}
{% block title %}Dev-Connect / Profiles{% endblock %}
{% block content %}

  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'profiles' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query" value="{{search_query}}"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          {% for profile in profiles %}
            <div class="column card">
              <div class="dev">
                <a href="{% url 'user-profile' profile.id %}" class="card__body">
                  <div class="dev__profile">
                    <img
                      class="avatar avatar--md"
                      src="{{profile.profile_image.url}}"
                      alt="image"
                    />
                    <div class="dev__meta">
                      <h3>{{profile.name}}</h3>
                      <h5>{{profile.short_intro|slice:"150"}}</h5>
                    </div>
                  </div>
                  <p class="dev__info">{{profile.bio|slice:"150"}}</p>
                  <div class="dev__skills">
                    {% for skill in profile.skill_set.all|slice:"1" %}
                      <span class="tag tag--pill tag--main">
                        <small>{{skill}}</small>
                      </span>
                    {% endfor %}
                  </div>
                </a>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      
      
    </section>

   <!-- ! we want to be able to use pagination anywhere in the template, it is just a key and value pairs, it will paginate all the profiles -->
    <!-- ! we also need the custom_range in the template -->
    <!--  -->
    {% include "pagination.html" with queryset=profiles custom_range=custom_range %}
  </main>



{% endblock content %}

basic/users/templates/users/skill_form.html
{% extends "main.html" %}
{% block title %}Form / Skill{% endblock %}


{% block content %}
    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form"  action="" method="POST">
                    {% csrf_token %}
                {% for field in form %}
                        <!-- Input:Text -->
                        <div class="form__field">
                            <label for="formInput#text">{{field.label}}</label>
                            {{field}}
                        </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Add Skill" />
                </form>
            </div>
        </div>
    </main>












{% endblock content %}

basic/users/templates/users/user-profile.html
{% extends "main.html" %}
{% block title %}profile -> page{% endblock %}





{% block content %}
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">

              {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
              {% endif %}

           
              {% if profile.social_facebook %}
                <li>
                  <a title="FaceBook" href="{{profile.social_facebook}}" target="_blank"><i class="im im-facebook"></i></a>
                </li>
              {% endif %}



              {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
              {% endif %}



              {% if profile.social_linkedln %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
              {% endif %}

              
              {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
              {% endif %}


              </ul>
              {% if request.user.profile.id != profile.id %}
            <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}

            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">


            {% for skill in topSkills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">{{skill.description}}</p>
              </div>
            {% endfor %}

             

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">




              {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill}}</small>
                </span>
              {% endfor %}


              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">



                {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="profile.html">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                        


                          <!-- ! This is a many to many relationship -->
                          {% for tag in project.tags.all %}  
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                        
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}


            </div>
          </div>
        </div>
      </div>
    </div>
  </main>








{% endblock content %}